// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSaiUznDxnnrZRhnWrteu0wAdtwhZsvtg',
    appId: '1:1020475219221:web:4fd6091bd9dd18badb1d1c',
    messagingSenderId: '1020475219221',
    projectId: 'instagramclone-f8be5',
    authDomain: 'instagramclone-f8be5.firebaseapp.com',
    storageBucket: 'instagramclone-f8be5.appspot.com',
    measurementId: 'G-1M5XNMG036',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwpIL1IY6bBJNvd64D7J58os7bpd5h2C0',
    appId: '1:1020475219221:android:28dd610006d11f2bdb1d1c',
    messagingSenderId: '1020475219221',
    projectId: 'instagramclone-f8be5',
    storageBucket: 'instagramclone-f8be5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwcGE-cxguw9YyqIEgPQL95HWUxqlx0K4',
    appId: '1:1020475219221:ios:1b32b24fe34bb01cdb1d1c',
    messagingSenderId: '1020475219221',
    projectId: 'instagramclone-f8be5',
    storageBucket: 'instagramclone-f8be5.appspot.com',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwcGE-cxguw9YyqIEgPQL95HWUxqlx0K4',
    appId: '1:1020475219221:ios:1b32b24fe34bb01cdb1d1c',
    messagingSenderId: '1020475219221',
    projectId: 'instagramclone-f8be5',
    storageBucket: 'instagramclone-f8be5.appspot.com',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSaiUznDxnnrZRhnWrteu0wAdtwhZsvtg',
    appId: '1:1020475219221:web:48558ee31ab3c5c6db1d1c',
    messagingSenderId: '1020475219221',
    projectId: 'instagramclone-f8be5',
    authDomain: 'instagramclone-f8be5.firebaseapp.com',
    storageBucket: 'instagramclone-f8be5.appspot.com',
    measurementId: 'G-3NQCZZBGX4',
  );
}
